version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    build:
      context: ./api
    ports:
      - "8080:8000"
    env_file: 
      - .env
    depends_on: 
      - rabbitmq