version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    restart: always
    image: redis:alpine
    # ports:
      # - "6379:6379"
  api:
    build:
      context: ./api
    ports:
      - "8080:8000"
    env_file: 
      - .env
    depends_on: 
      - rabbitmq
  assembler:
    build:
      context: ./assembler
    volumes: 
      - ./common:/common
    env_file: 
      - .env
    depends_on: 
      - rabbitmq
  dispatcher:
    build:
      context: ./dispatcher
    volumes: 
      - ./common:/common
    env_file: 
      - .env
    depends_on: 
      - rabbitmq
    